<?php
$title = $this->translate('Add new album');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$album = $this->form->get('album');
$form->setAttribute('action', $this->url('album/default', array('controller'=>'album', 'action' => 'add')));

$form->prepare();
echo $this->form()->openTag($form);
?>
    <div class="form-group <?php if ($this->formElementErrors($album->get('title'))) echo "has-error" ?>">
        <label class="control-label"><?php echo $this->formLabel($album->get('title')) ?></label>
        <?php
        $album  ->get('title')
                ->setAttribute('class', 'form-control')
                ->setAttribute('placeholder', 'Title');

        echo $this->formElement($album->get('title'));
        if ($this->formElementErrors($album->get('title'))) : ?>
            <?php
            echo $this->formElementErrors()
                ->setMessageOpenFormat('<p class="help-block">')
                ->setMessageSeparatorString('</p><p class="help-block">')
                ->setMessageCloseString('</p>')
                ->render($album->get('title'));
            ?>
        <?php endif; ?>
    </div>
    <div class="form-group <?php if ($this->formElementErrors($album->get('artist'))) echo "has-error" ?>">
        <label class="control-label"><?php echo $this->formLabel($album->get('artist')) ?></label>
        <?php
        $album  ->get('artist')
                ->setAttribute('class', 'form-control')
                ->setAttribute('placeholder', 'Artist');
                
        echo $this->formElement($album->get('artist'));
        if ($this->formElementErrors($album->get('artist'))) : ?>
            <?php
            echo $this->formElementErrors()
                ->setMessageOpenFormat('<p class="help-block">')
                ->setMessageSeparatorString('</p><p class="help-block">')
                ->setMessageCloseString('</p>')
                ->render($album->get('artist'));
            ?>
        <?php endif; ?>
    </div>
<?php
echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-success'));
echo $this->formHidden($this->form->get('add_album_csrf'));
echo $this->form()->closeTag() ?>