<?php
// module/Album/view/album/album/add.phtml:

$title = $this->translate('Add new album');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('album', array('action' => 'add')));
$form->prepare();
$this->translate('Add');

echo $this->form()->openTag($form);

foreach ($form->get('album') as $element) : ?>
	<div style="width: 330px;" class="form-group <?php if ($this->formElementErrors($element)) echo "has-error" ?>">
        <label class="control-label"><?php echo $element->getLabel() ?></label>
        <?php
        $element->setAttribute('class', 'form-control')
                ->setAttribute('placeholder', $element->getLabel());

           

        echo $this->formElement($element);
        if ($this->formElementErrors($element)) : ?>
            <?php
            echo $this->formElementErrors()
                ->setMessageOpenFormat('<p class="help-block">')
                ->setMessageSeparatorString('</p><p class="help-block">')
                ->setMessageCloseString('</p>')
                ->render($element);
            ?>
        <?php endif; ?>
    </div>
<?php
endforeach;
echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-success'));
echo $this->formHidden($this->form->get('add_album_csrf'));
echo $this->form()->closeTag() ?>
