<?php
// module/Album/view/album/album/add.phtml:

$title = $this->translate('Add new album');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('album', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
//Ceci est un view helper pour afficher le formulaire
echo $this->formCollection($form);
echo $this->form()->closeTag();