 <?php
 // module/Album/view/album/album/delete.phtml:

 $title = $this->translate('Delete album');
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <p><?php echo $this->translate('Are you sure that you want to delete');?>
     '<?php echo $this->escapeHtml($this->album->getTitle()); ?>' by
     '<?php echo $this->escapeHtml($this->album->getArtist()); ?>'?
 </p>
 <?php
 $url = $this->url('album/default', array(
 	 'controller'=>'album',
     'action' => 'delete',
     'id'     => $this->id,
 ));
 ?>

 <form action="<?php echo $url; ?>" method="post">
 <div>
     <input type="hidden" name="id" value="<?php echo $this->album->getId(); ?>" />
     <input type="hidden" id="response" name="response" value="" />
     <input type="button" id="yes" name="del" value="<?php echo $this->translate('Yes');?>" onclick='makeDecision("yes", $(this), "no")'/>
     <input type="button" id="no" name="del" value="<?php echo $this->translate('No');?>"  onclick='makeDecision("no",$(this), "yes")'/>
     <div class="margin-top-5">
     	<input type="submit" id="confirm" value="<?php echo $this->translate('confirm');?>" disabled="disabled"/>
     </div>
 </div>
 </form>

<script type="text/javascript">
	function makeDecision(decision, from, toEnable)
	{
		var toDisable = from.attr('id');
		$("#response").attr("value", decision);
		$("#"+toDisable).attr("disabled","disabled");
		$("#"+toEnable).removeAttr("disabled");
		$("#confirm").removeAttr("disabled");
	}
</script>