 <?php
 // module/Album/view/album/album/delete.phtml:

 $title = $this->translate('Delete album');
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <p><?php echo $this->translate('Are you sure that you want to delete');?>
     '<?php echo $this->escapeHtml($this->album->getTitle()); ?>' by
     '<?php echo $this->escapeHtml($this->album->getArtist()); ?>'?
 </p>
 <?php
 $url = $this->url('album', array(
     'action' => 'delete',
     'id'     => $this->id,
 ));
 ?>
 <form action="<?php echo $url; ?>" method="post">
 <div>
     <input type="hidden" name="id" value="<?php echo $this->album->getId(); ?>" />
     <input type="submit" name="del" value="<?php echo $this->translate('Yes');?>" />
     <input type="submit" name="del" value="<?php echo $this->translate('No');?>" />
 </div>
 </form>