<?php
 // module/Album/view/album/album/edit.phtml:

 $title = $this->translate('Edit album');
 $this->headTitle($title);
 ?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;

$post = $this->form->get('album');
$form->setAttribute('action', $this->url(
    'album',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();


echo $this->form()->openTag($form);
echo $this->formRow($post->get('title'));
echo $this->formRow($post->get('artist'));
echo $this->formSubmit($this->form->get('submit'));
echo $this->formHidden($this->form->get('edit_album_csrf'));
echo $this->form()->closeTag();
