<?php
 // module/Album/view/album/album/edit.phtml:

 $title = $this->translate('Edit album');
 $this->headTitle($title);
 ?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;

$post = $this->form->get('album');
$form->setAttribute('action', $this->url(
    'album',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();
echo $this->form()->openTag($form);

foreach ($form->get('album') as $element) : ?>
	<div style="width: 330px;" class="form-group <?php if ($this->formElementErrors($element)) echo "has-error" ?>">
        <label class="control-label"><?php echo $element->getLabel() ?></label>
        <?php
        $element->setAttribute('class', 'form-control')
                ->setAttribute('placeholder', $element->getLabel());
        echo $this->formElement($element);
        if ($this->formElementErrors($element)) : ?>
            <?php
            echo $this->formElementErrors()
                ->setMessageOpenFormat('<p class="help-block">')
                ->setMessageSeparatorString('</p><p class="help-block">')
                ->setMessageCloseString('</p>')
                ->render($element);
            ?>
        <?php endif; ?>
    </div>
<?php
endforeach;
echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-success'));
echo $this->formHidden($this->form->get('edit_album_csrf'));
echo $this->form()->closeTag() ?>
