<?php echo $this->doctype(); ?>

<?php
$children = $this->viewModel()
                 ->getCurrent()
                 ->getChildren();
    $ourView  = $children[0];
?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/fam-icons.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css'); ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2" class="logoCorporateRedim"/></a>
                </div>
                <div class="collapse navbar-collapse">
                    <?php echo $this->navigation('navigation')->menu()->setMaxDepth(0)->setUlClass('nav navbar-nav')?>

                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <?php 
                                    //On gère ici l'affichage des langue dans la navigation on change la 
                                    //couleur du drapeau selon la langue
                                    if($this->navigation()->getTranslator()->getLocale() == 'fr_FR')
                                    {
                                        echo '<span class="flag fr"></span> FR <span class="caret"></span>';
                                    } else {
                                        echo '<span class="flag gb"></span> GB <span class="caret"></span>';
                                    }
                                ?>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href='<?php echo $this->url('changelocale', array('locale'=>'fr_FR', 'redirecturl'=>urlencode($this->absoluteUrl()))); ?>'>
                                    <span class="flag fr"></span> Français
                                </a></li>
                                <li><a href='<?php echo $this->url('changelocale', array('locale'=>'en_US', 'redirecturl'=>urlencode($this->absoluteUrl()))); ?>'>
                                    <span class="flag gb"></span> English
                                </a></li>
                            </ul>
                        </li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
             <?php 
                //Affichage des messages de type FlashMessages (message d'informations)
                if (isset($ourView->flashMessages) && count($ourView->flashMessages)) : ?>
                    <?php foreach ($ourView->flashMessages as $fMessage) : ?>
                    <?php foreach ($fMessage as $kMsg=>$valMsg) : ?>
                        <div class="alert  alert-<?=$kMsg?>">
                            <a href="#" class="close" data-dismiss="alert">&times;</a>
                            <p><?=$valMsg?></p>
                        </div>
                    <?php endforeach; ?>
                    <?php endforeach; ?>
                <?php endif; 
                echo $this->navigation('navigation')->breadcrumbs()->setMinDepth(0)->setPartial(array('partial/breadcrumbs.phtml', 'Application')); 
                echo $this->content; 
            ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
