<?php echo $this->doctype(); ?>
<html lang="<?php echo substr($this->navigation()->getTranslator()->getLocale(), 0, 2); ?>">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Mylink by DocSourcing')
            ->setSeparator(' - ')
            ->setAutoEscape(false) 
        ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(
                array(
                    'rel' => 'shortcut icon', 
                    'type' => 'image/vnd.microsoft.icon', 
                    'href' => $this->basePath() . '/img/favicon.ico'
                )
            )
            ->prependStylesheet($this->basePath() . '/css/style.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap-override.css')
            ->prependStylesheet('http://fonts.googleapis.com/css?family=Open+Sans')
            ->prependStylesheet($this->basePath() . '/font-awesome/css/font-awesome.min.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9'))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9'))
        ?>

    </head>
    <body>
        <div id="wrapper">
            <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                </div>
                <div class="collapse navbar-collapse navbar-ex1-collapse">
                  <ul class="nav navbar-nav side-nav">
                        <li class="bg-special-home">
                            <a href="<?php echo $this->url('home') ?>">
                                <?= $this->translate('Home')?> 
                                <i class="fa fa-home icon-home"></i>
                            </a>
                        </li>
                        <hr class="hr-menu" />
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <?php 
                                    //On gère ici l'affichage des langue dans la navigation on change la 
                                    //couleur du drapeau selon la langue
                                    if($this->navigation()->getTranslator()->getLocale() == 'fr_FR')
                                    {
                                        echo '<span class="flag fr"></span> FR <span class="caret"></span>';
                                    } else {
                                        echo '<span class="flag gb"></span> GB <span class="caret"></span>';
                                    }
                                ?>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href='<?php echo $this->url('changelocale', array('locale'=>'fr_FR', 'redirecturl'=>urlencode($this->absoluteUrl()))); ?>'>
                                    <span class="flag fr"></span> Français
                                </a></li>
                                <li><a href='<?php echo $this->url('changelocale', array('locale'=>'en_US', 'redirecturl'=>urlencode($this->absoluteUrl()))); ?>'>
                                    <span class="flag gb"></span> English
                                </a></li>
                            </ul>
                        </li>
                        <hr class="hr-menu" />
                        <?php echo $this->navigation('navigation')->menu()->setPartial('partial/menu')->render();?>
                        <hr class="hr-menu" />
                    </ul>


                    <!-- 
                        **********************************************************************************
                        **                                 Code d'exemple                               **
                        **                                                                              **
                        **********************************************************************************
                     -->
                    <ul class="nav navbar-nav navbar-right navbar-user">
                        <li class="dropdown messages-dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-envelope"></i> Messages <span class="badge">7</span> <b class="caret"></b></a>
                          <ul class="dropdown-menu">
                            <li class="dropdown-header">7 New Messages</li>
                            <li class="message-preview">
                              <a href="#">
                                <span class="avatar"><img src="http://placehold.it/50x50"></span>
                                <span class="name">John Smith:</span>
                                <span class="message">Hey there, I wanted to ask you something...</span>
                                <span class="time"><i class="fa fa-clock-o"></i> 4:34 PM</span>
                              </a>
                            </li>
                            <li class="divider"></li>
                            <li class="message-preview">
                              <a href="#">
                                <span class="avatar"><img src="http://placehold.it/50x50"></span>
                                <span class="name">John Smith:</span>
                                <span class="message">Hey there, I wanted to ask you something...</span>
                                <span class="time"><i class="fa fa-clock-o"></i> 4:34 PM</span>
                              </a>
                            </li>
                            <li class="divider"></li>
                            <li class="message-preview">
                              <a href="#">
                                <span class="avatar"><img src="http://placehold.it/50x50"></span>
                                <span class="name">John Smith:</span>
                                <span class="message">Hey there, I wanted to ask you something...</span>
                                <span class="time"><i class="fa fa-clock-o"></i> 4:34 PM</span>
                              </a>
                            </li>
                            <li class="divider"></li>
                            <li><a href="#">View Inbox <span class="badge">7</span></a></li>
                          </ul>
                        </li>
                        <li class="dropdown alerts-dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell"></i> Alerts <span class="badge">3</span> <b class="caret"></b></a>
                          <ul class="dropdown-menu">
                            <li><a href="#">Default <span class="label label-default">Default</span></a></li>
                            <li><a href="#">Primary <span class="label label-primary">Primary</span></a></li>
                            <li><a href="#">Success <span class="label label-success">Success</span></a></li>
                            <li><a href="#">Info <span class="label label-info">Info</span></a></li>
                            <li><a href="#">Warning <span class="label label-warning">Warning</span></a></li>
                            <li><a href="#">Danger <span class="label label-danger">Danger</span></a></li>
                            <li class="divider"></li>
                            <li><a href="#">View All</a></li>
                          </ul>
                        </li>
                        <li class="dropdown user-dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> John Smith <b class="caret"></b></a>
                          <ul class="dropdown-menu">
                            <li><a href="#"><i class="fa fa-user"></i> Profile</a></li>
                            <li><a href="#"><i class="fa fa-envelope"></i> Inbox <span class="badge">7</span></a></li>
                            <li><a href="#"><i class="fa fa-gear"></i> Settings</a></li>
                            <li class="divider"></li>
                            <li><a href="#"><i class="fa fa-power-off"></i> Log Out</a></li>
                          </ul>
                        </li>
                      </ul>
                      <!-- 
                        **********************************************************************************
                        **                                Fin Code d'exemple                            **
                        **                                                                              **
                        **********************************************************************************
                     -->
                </div>
            </nav>
            <div id="page-wrapper">
                <div class="row">
                    <?php
                        if ($this->flashMessages) {
                            foreach ($this->flashMessages as $context => $messages) {
                              echo '<div class="alert alert-dismissable alert-' . $context . '">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                                     &times;
                                 </button>
                              ';
                              foreach ($messages as $message) {
                                echo '<p>' . $this->translate($message) . '</p>';
                              }
                              echo '</div>';
                            }
                        }
                        echo $this->navigation('navigation')->breadcrumbs()->setMinDepth(0)->setPartial(array('partial/breadcrumbs.phtml', 'Application')); 
                        echo $this->content; 
                    ?>
                </div>
                <hr>
                <footer>
                    <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
                </footer>
            </div> <!-- /container -->
            <?php echo $this->inlineScript() ?>
        </div>
    </body>
</html>
